package plugin

import (
	"github.com/LarsArtmann/templates/repo-validation/domain"
)

// TypeScriptPlugin implements the TypeScript file group plugin
type TypeScriptPlugin struct{}

// Files checked by this plugin:
// - package.json: Defines project metadata and dependencies
// - tsconfig.json: TypeScript compiler configuration
// - .eslintrc.json: Code linting rules
// - .prettierrc: Code formatting rules
// - jest.config.js: Test framework configuration

// Name returns the name of the plugin
func (p *TypeScriptPlugin) Name() string {
	return "typescript"
}

// Description returns the description of the plugin
func (p *TypeScriptPlugin) Description() string {
	return "TypeScript/JavaScript related files"
}

// Files returns the files checked by this plugin
func (p *TypeScriptPlugin) Files() []domain.File {
	return []domain.File{
		{
			Path:     "package.json",
			Required: true,
			Category: domain.CategoryTypeScript,
			Priority: domain.PriorityMustHave,
			Template: "package.json.tmpl",
		},
		{
			Path:     "package-lock.json",
			Required: false,
			Category: domain.CategoryTypeScript,
			Priority: domain.PriorityShouldHave,
			Template: "", // Generated by npm, not from a template
		},
		{
			Path:     "yarn.lock",
			Required: false,
			Category: domain.CategoryTypeScript,
			Priority: domain.PriorityShouldHave,
			Template: "", // Generated by yarn, not from a template
		},
		{
			Path:     "pnpm-lock.yaml",
			Required: false,
			Category: domain.CategoryTypeScript,
			Priority: domain.PriorityShouldHave,
			Template: "", // Generated by pnpm, not from a template
		},
		{
			Path:     "tsconfig.json",
			Required: true,
			Category: domain.CategoryTypeScript,
			Priority: domain.PriorityMustHave,
			Template: "tsconfig.json.tmpl",
		},
		{
			Path:     ".eslintrc.json",
			Required: false,
			Category: domain.CategoryTypeScript,
			Priority: domain.PriorityShouldHave,
			Template: ".eslintrc.json.tmpl",
		},
		{
			Path:     ".prettierrc",
			Required: false,
			Category: domain.CategoryTypeScript,
			Priority: domain.PriorityShouldHave,
			Template: ".prettierrc.tmpl",
		},
		{
			Path:     "jest.config.js",
			Required: false,
			Category: domain.CategoryTypeScript,
			Priority: domain.PriorityShouldHave,
			Template: "jest.config.js.tmpl",
		},
	}
}
